name: Deploy

on:
  push:
    branches: 
      - "master"

jobs:
  check-backend-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.check_backend.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for backend changes
        id: check_backend
        run: |
          # Ensure we have access to previous commits
          git fetch --depth=2
          
          # Check if any backend files have changed
          if git diff --name-only HEAD~1 HEAD | grep -q '^Server/'; then
            echo "changed=true" >> $GITHUB_ENV
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_ENV
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  check-frontend-changes:
    runs-on: ubuntu-latest
    needs: check-backend-changes
    outputs:
      frontend_changed: ${{ steps.check_frontend.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for frontend changes
        id: check_frontend
        run: |
          # Ensure we have access to previous commits
          git fetch --depth=2

          # Check if any frontend files have changed
          if git diff --name-only HEAD~1 HEAD | grep -q '^Client/'; then
            echo "changed=true" >> $GITHUB_ENV
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_ENV
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  deploy-backend:
    runs-on: ubuntu-latest
    needs: check-backend-changes
    if: needs.check-backend-changes.outputs.backend_changed == 'true'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.SERVER_VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove .vercel directory (if exists)
        run: rm -rf .vercel

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: check-frontend-changes
    if: needs.check-frontend-changes.outputs.frontend_changed == 'true'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.REACT_VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove .vercel directory (if exists)
        run: rm -rf .vercel

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
