name: Test Backend

on:
  push:
    branches:
      - master
      - development
    paths:
      - 'Server/**'
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test
